name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run rustfmt
        run: cargo fmt --all --check

      - name: Run clippy
        run: cargo clippy

      - name: Build release binary
        run: cargo build --release --target x86_64-unknown-linux-gnu

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: website-ssh-linux-x86_64
          path: target/x86_64-unknown-linux-gnu/release/website-ssh
          retention-days: 30

