name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    container: rust:1.88-bookworm

    steps:
      - uses: actions/checkout@v4

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: debian-bullseye-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run rustfmt
        run: |
          cargo fmt --all --check

      - name: Run clippy
        run: |
          cargo clippy --all-targets --all-features -- -D warnings

      - name: Build release binary
        run: |
          cargo build --release

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: website-ssh-linux-x86_64
          path: target/release/website-ssh
          retention-days: 30
